//! `qalam` — a thin command-line front end over `qalam-core`, for eyeballing what
//! the library sees while the pipeline is being built.
//!
//! ```text
//! qalam inspect <file.pdf>          # pages, geometry, fonts, recoverability hint
//! qalam raw     <file.pdf> [page]   # dump a page's raw content stream (default 1)
//! qalam glyphs  <file.pdf> [page]   # L1 output: positioned, styled glyph codes
//! qalam text    <file.pdf> [page]   # L2 output: codes resolved through /ToUnicode
//! ```

use std::process::ExitCode;

use qalam_core::{AssumedWidths, CodeToUnicode, FontMap, Pdf};

/// # Rust lesson: `main` can return
///
/// Returning [`ExitCode`] lets us set the process exit status without calling
/// `std::process::exit`, which would skip destructors. `ExitCode::FAILURE` is 1.
fn main() -> ExitCode {
    // `args()` yields the program name first, so skip it.
    let args: Vec<String> = std::env::args().skip(1).collect();

    // Matching on a slice of strings: `as_slice` gives us `&[String]`, and the
    // patterns destructure it by length. `..` means "and anything else".
    let result = match args.as_slice() {
        [cmd, path] if cmd == "inspect" => inspect(path),
        [cmd, path] if cmd == "raw" => raw(path, 1),
        [cmd, path] if cmd == "glyphs" => glyphs(path, 1),
        [cmd, path] if cmd == "text" => text(path, 1),
        // Both page-taking commands parse their argument the same way, so they
        // share one arm and dispatch on the command name inside it.
        [cmd, path, page] if cmd == "raw" || cmd == "glyphs" || cmd == "text" => {
            match page.parse() {
                Ok(n) if cmd == "raw" => raw(path, n),
                Ok(n) if cmd == "glyphs" => glyphs(path, n),
                Ok(n) => text(path, n),
                Err(_) => {
                    eprintln!("error: `{page}` is not a page number");
                    return ExitCode::FAILURE;
                }
            }
        }
        _ => {
            usage();
            return ExitCode::FAILURE;
        }
    };

    match result {
        Ok(()) => ExitCode::SUCCESS,
        Err(e) => {
            // `{e}` uses the Display impl generated by thiserror in error.rs.
            eprintln!("error: {e}");
            ExitCode::FAILURE
        }
    }
}

fn usage() {
    eprintln!(
        "qalam — Arabic PDF text extraction\n\
         \n\
         usage:\n\
         \x20 qalam inspect <file.pdf>          pages, geometry and font resources\n\
         \x20 qalam raw <file.pdf> [page]       raw content stream of a page (default 1)\n\
         \x20 qalam glyphs <file.pdf> [page]    positioned, styled glyph codes (L1)\n\
         \x20 qalam text <file.pdf> [page]      codes resolved through /ToUnicode (L2)"
    );
}

/// Print what L0 can see: page geometry plus a per-font recoverability hint.
fn inspect(path: &str) -> qalam_core::Result<()> {
    let pdf = Pdf::open(path)?;
    println!("{path}: {} page(s)", pdf.page_count());

    for page in pdf.pages() {
        let mb = page.media_box;
        println!(
            "\npage {} — {:.1} x {:.1} pt, rotate {}°",
            page.number,
            mb.width(),
            mb.height(),
            page.rotation.degrees()
        );

        if page.fonts.is_empty() {
            // No fonts at all is itself a strong signal: most likely the page is
            // a scanned image, so there is no text layer to extract.
            println!("  (no font resources — likely a scanned page)");
            continue;
        }

        for font in &page.fonts {
            // The hint we can give before parsing a single CMap.
            let hint = match font.code_to_unicode {
                CodeToUnicode::ToUnicode => "ToUnicode present — recoverable",
                CodeToUnicode::EncodingOnly => "no ToUnicode, /Encoding only — uncertain",
                CodeToUnicode::None => "no ToUnicode, no /Encoding — likely needs OCR",
            };
            println!(
                "  /{:<8} {:<10} {:<28} codes={} — {}",
                font.resource_name,
                font.subtype,
                // `as_deref` turns `&Option<String>` into `Option<&str>` so we can
                // supply a plain `&str` default without allocating.
                font.base_font.as_deref().unwrap_or("(no /BaseFont)"),
                if font.is_two_byte() {
                    "2-byte"
                } else {
                    "1-byte"
                },
                hint,
            );
            if let Some(enc) = &font.encoding {
                println!("               /Encoding {enc}");
            }
        }
    }
    Ok(())
}

/// Dump a page's content stream so we can read the operators by eye.
///
/// The stream is bytes, not text — it contains binary string literals — so we
/// print it lossily rather than pretending it is UTF-8.
fn raw(path: &str, page: u32) -> qalam_core::Result<()> {
    let pdf = Pdf::open(path)?;
    let content = pdf.page_content(page)?;
    println!("{}", String::from_utf8_lossy(&content));
    Ok(())
}

/// Print what L1 recovered: every glyph code with its position and styling.
///
/// The codes are **not** characters yet — resolving them needs the font's
/// `/ToUnicode` map, which is the next layer. What this proves is that we are
/// tracking the graphics state correctly: positions, effective sizes and
/// colours should match what the page looks like.
fn glyphs(path: &str, page: u32) -> qalam_core::Result<()> {
    let pdf = Pdf::open(path)?;

    // L1 needs the page's font list to know whether codes are 1 or 2 bytes.
    let info = pdf
        .pages()
        .into_iter()
        .find(|p| p.number == page)
        .ok_or(qalam_core::Error::PageNotFound(page))?;

    let content = pdf.page_content(page)?;
    // `AssumedWidths` is the placeholder until `font.rs` supplies real metrics.
    let out = qalam_core::interpret(&content, &info.fonts, &AssumedWidths);

    println!("page {page}: {} glyph(s)", out.glyphs.len());
    if out.skipped_forms > 0 {
        println!(
            "  note: {} form XObject(s) not entered — they may contain text",
            out.skipped_forms
        );
    }

    // Group consecutive glyphs that share a style and a baseline, so the output
    // reads as runs rather than one line per glyph. This is a crude preview of
    // what L3 will do properly with geometry.
    let mut run_start: Option<usize> = None;
    for i in 0..out.glyphs.len() {
        let start = *run_start.get_or_insert(i);
        let same_run = i > start
            && out.glyphs[i].style.merges_with(&out.glyphs[start].style)
            && (out.glyphs[i].y - out.glyphs[start].y).abs() < 0.5;

        // Flush when the run ends, or when we reach the last glyph.
        if !same_run && i > start {
            print_run(&out.glyphs[start..i]);
            run_start = Some(i);
        }
    }
    if let Some(start) = run_start {
        print_run(&out.glyphs[start..]);
    }
    Ok(())
}

/// Print one uniformly-styled run of glyphs.
fn print_run(run: &[qalam_core::Glyph]) {
    let Some(first) = run.first() else { return };
    let style = &first.style;

    println!(
        "\n  /{} {:.2}pt {} {}{}",
        style.font,
        style.size,
        style.color.to_css_hex(),
        if style.color.is_black() {
            "(black)"
        } else {
            ""
        },
        if style.render_mode.is_visible() {
            String::new()
        } else {
            format!(" [{:?} — INVISIBLE]", style.render_mode)
        },
    );
    println!(
        "    at ({:.1}, {:.1}), {} glyph(s)",
        first.x,
        first.y,
        run.len()
    );

    // The codes themselves, as hex — directly comparable with the `<...>Tj`
    // hex strings in `qalam raw` output.
    let codes: Vec<String> = run.iter().map(|g| format!("{:04X}", g.code)).collect();
    println!("    {}", codes.join(" "));
}

/// Resolve a page's glyph codes through their fonts and print the result.
///
/// **The output is expected to look wrong.** This is the M1 checkpoint from
/// PLAN.md: Arabic here is still in *visual* order and still made of
/// presentation forms, because that is exactly what the PDF stores. Seeing the
/// garbage is the point — M2 fixes it with bidi reordering followed by NFKC,
/// in that order.
fn text(path: &str, page: u32) -> qalam_core::Result<()> {
    let pdf = Pdf::open(path)?;
    let info = pdf
        .pages()
        .into_iter()
        .find(|p| p.number == page)
        .ok_or(qalam_core::Error::PageNotFound(page))?;

    // L2: parse every /ToUnicode CMap on the page. The same map also supplies
    // real advance widths, so L1 no longer needs `AssumedWidths`.
    let fonts = FontMap::from_raw(pdf.page_raw_fonts(page)?);

    for font in fonts.iter() {
        println!(
            "font /{}: {} code(s) mappable, {}-byte codes",
            font.resource_name,
            font.to_unicode.len(),
            if font.two_byte { 2 } else { 1 },
        );
    }

    let content = pdf.page_content(page)?;
    let out = qalam_core::interpret(&content, &info.fonts, &fonts);

    // Group glyphs into lines by their baseline. Crude on purpose: proper
    // geometric grouping is L3's job, and doing it here would prejudge it.
    let mut line = String::new();
    // `Option<f64>`, not `f64::NAN`: every comparison with NaN is false, so a
    // NaN sentinel would make the "new line?" test never fire and pile the
    // whole page onto one line. The type system makes "no baseline yet" a case
    // you have to handle rather than a value that quietly misbehaves.
    let mut baseline: Option<f64> = None;
    let mut unresolved = 0usize;
    let mut total = 0usize;

    for glyph in &out.glyphs {
        let new_line = baseline.is_none_or(|b| (glyph.y - b).abs() > 0.5);
        if new_line {
            flush(&mut line, baseline);
            baseline = Some(glyph.y);
        }
        total += 1;
        match fonts.decode(&glyph.style.font, glyph.code) {
            Some(text) => line.push_str(&text),
            None => {
                // The honest marker: a code no font could resolve. Never a
                // silently dropped character.
                unresolved += 1;
                line.push('\u{FFFD}');
            }
        }
    }
    flush(&mut line, baseline);

    println!("\n{unresolved} of {total} glyph(s) unresolved");
    if out.skipped_forms > 0 {
        println!("{} form XObject(s) not entered", out.skipped_forms);
    }
    Ok(())
}

/// Print one accumulated line and clear the buffer.
///
/// Takes `&mut String` and empties it, so the caller reuses one allocation
/// across the whole page rather than building a fresh string per line.
fn flush(line: &mut String, baseline: Option<f64>) {
    if let (false, Some(y)) = (line.is_empty(), baseline) {
        println!("[y={y:7.1}] {line}");
        line.clear();
    }
}
